### ISSUE TITLE
Object class KmsWebRtcBundleConnection doesn't implement property 'rtp-socket' ...

### ISSUE THREAD

**Issue by sledz** [ESTOS/kms-elements#1]
Unfortunately commit 4624f7de5ceb585d2d9ad99bce871f44e97f345b leads to some critical runtime errors. :(

> (kurento-media-server.exe:11200): GLib-GObject-[1;35mCRITICAL[0m **: Object class KmsWebRtcBundleConnection doesn't implement property 'rtp-socket' from interface 'KmsIRtpConnection'
>
> (kurento-media-server.exe:11200): GLib-GObject-[1;35mCRITICAL[0m **: Object class KmsWebRtcBundleConnection doesn't implement property 'rtcp-socket' from interface 'KmsIRtpConnection'
>
> (kurento-media-server.exe:11200): GLib-GObject-[1;35mCRITICAL[0m **: Object class KmsWebRtcBundleConnection doesn't implement property 'finalize-socket' from interface 'KmsIRtpConnection'

**Comment by stemi1** [comment]
Thx for reporting.
A Fix is in the works.

**Comment by rolfbsts** [comment]
Commit https://github.com/ESTOS/kms-elements/commit/71d4c213a1435957e1809c88e2901535ff55c7ce should fix it. Was not a problem.
